// See https://aka.ms/new-console-template for more information
// the below represents the body of the main method generated by compiler 
// top-level statements = compiler generates class and method elements for main program
Console.WriteLine("Hello, World!");

